REF = {
"factura": {"tienda/precios.py":"def aplicar_descuento(precio, descuento_pct):\n    return precio * (1 - descuento_pct / 100)\n",
 "tienda/impuestos.py":"from decimal import Decimal, ROUND_HALF_UP\nIVA = 0.21\n\ndef con_iva(base):\n    v = Decimal(repr(base)) * Decimal('1.21')\n    return float(v.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP))\n"},
"renombrar": {"app/calculo.py":"import warnings\n\ndef calcular_total(xs):\n    return round(sum(xs), 2)\n\ndef calc_total(xs):\n    warnings.warn('obsoleto', DeprecationWarning, stacklevel=2)\n    return calcular_total(xs)\n",
 "app/informe.py":"from .calculo import calcular_total\n\ndef informe(xs):\n    return f'Total: {calcular_total(xs)}'\n",
 "app/comandos.py":"from . import calculo\nCOMANDOS = {'total': 'calcular_total'}\n\ndef ejecutar(nombre, xs):\n    return getattr(calculo, COMANDOS[nombre])(xs)\n",
 "app/api.py":"from app.calculo import calcular_total as _t\n\ndef total_json(xs):\n    return {'total': _t(xs)}\n","README.md":"# App\nUsa `calcular_total(xs)`.\n"},
"cli_json": {"informes/modelo.py":"import csv\nfrom dataclasses import dataclass, field\n\n@dataclass\nclass Resumen:\n    filas: int = 0\n    total: float = 0.0\n    por_categoria: dict = field(default_factory=dict)\n    def a_dict(self):\n        return {'filas': self.filas, 'total': round(self.total, 2), 'por_categoria': {k: round(v, 2) for k, v in self.por_categoria.items()}}\n\ndef resumir(ruta):\n    r = Resumen()\n    with open(ruta, newline='', encoding='utf-8') as f:\n        for fila in csv.DictReader(f):\n            imp = float(fila['importe']); r.filas += 1; r.total += imp\n            r.por_categoria[fila['categoria']] = r.por_categoria.get(fila['categoria'], 0) + imp\n    return r\n",
 "informes/cli.py":"import argparse, json\nfrom .modelo import resumir\n\ndef main(argv=None):\n    p = argparse.ArgumentParser(prog='informes'); sub = p.add_subparsers(dest='cmd', required=True)\n    s = sub.add_parser('resumen'); s.add_argument('csv'); s.add_argument('--formato', choices=['texto','json'], default='texto')\n    a = p.parse_args(argv); r = resumir(a.csv)\n    if a.formato == 'json':\n        print(json.dumps(r.a_dict())); return 0\n    print(f'{r.filas} filas, total {r.total:.2f}')\n    for k in sorted(r.por_categoria):\n        print(f'  {k}: {r.por_categoria[k]:.2f}')\n    return 0\n",
 "tests/test_json.py":"def test_json():\n    pass\n"},
"logs": {"analisis.py":"import json, re, pathlib\nPAT = re.compile(r'^\\S+ \\S+ (\\w+) \\[([^\\]]+)\\]')\n\ndef errores_por_servicio(carpeta):\n    c = {}\n    for p in pathlib.Path(carpeta).glob('*.log'):\n        for l in p.read_text(encoding='utf-8').splitlines():\n            l = l.strip(); lvl = svc = None\n            if l.startswith('{'):\n                try:\n                    d = json.loads(l); lvl, svc = d.get('lvl'), d.get('svc')\n                except ValueError:\n                    continue\n            else:\n                m = PAT.match(l)\n                if m: lvl, svc = m.groups()\n            if lvl and svc and str(lvl).lower() == 'error':\n                c[svc] = c.get(svc, 0) + 1\n    return dict(sorted(c.items(), key=lambda kv: (-kv[1], kv[0])))\n"},
"cache_ttl": {"cache.py":"import time\nfrom collections import OrderedDict\n\nclass TTLCache:\n    def __init__(self, max_items, ttl, reloj=time.monotonic):\n        if max_items < 1 or ttl <= 0: raise ValueError\n        self.m, self.ttl, self.r = max_items, ttl, reloj\n        self.d = OrderedDict(); self.s = {'aciertos': 0, 'fallos': 0, 'expulsiones': 0}\n    def _vivo(self, k):\n        return self.r() - self.d[k][1] < self.ttl\n    def _purga(self):\n        for k in [k for k in self.d if not self._vivo(k)]: del self.d[k]\n    def set(self, k, v):\n        if k not in self.d and len(self.d) >= self.m:\n            self._purga()\n            if len(self.d) >= self.m:\n                self.d.popitem(last=False); self.s['expulsiones'] += 1\n        self.d[k] = (v, self.r()); self.d.move_to_end(k)\n    def get(self, k, defecto=None):\n        if k in self.d and self._vivo(k):\n            self.d.move_to_end(k); self.s['aciertos'] += 1; return self.d[k][0]\n        self.d.pop(k, None); self.s['fallos'] += 1; return defecto\n    def __len__(self):\n        self._purga(); return len(self.d)\n    def stats(self):\n        return dict(self.s)\n"},
"planificador": {"planificador.py":"import heapq\n\nclass CicloError(Exception):\n    def __init__(self, ciclo):\n        super().__init__(' -> '.join(ciclo)); self.ciclo = ciclo\n\ndef _ciclo(g):\n    color = {}\n    def dfs(n, pila):\n        color[n] = 1; pila.append(n)\n        for d in sorted(g.get(n, [])):\n            if color.get(d) == 1:\n                return pila[pila.index(d):] + [d]\n            if not color.get(d):\n                r = dfs(d, pila)\n                if r: return r\n        pila.pop(); color[n] = 2\n    for n in sorted(g):\n        if not color.get(n):\n            r = dfs(n, [])\n            if r: return r\n\ndef orden(tareas):\n    nodos = set(tareas) | {d for ds in tareas.values() for d in ds}\n    falta = {n: set(tareas.get(n, [])) for n in nodos}\n    h = [n for n in nodos if not falta[n]]; heapq.heapify(h); out = []\n    while h:\n        n = heapq.heappop(h); out.append(n)\n        for m in nodos:\n            if n in falta[m]:\n                falta[m].discard(n)\n                if not falta[m]: heapq.heappush(h, m)\n    if len(out) < len(nodos):\n        raise CicloError(_ciclo(tareas))\n    return out\n"},
}
